ApplicantsAndJobs/Web/Models/ErrorViewModel.cs
using System;

namespace Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ApplicantsAndJobs/Web/ViewModels/HomeViewModels/IndexViewModel.cs
 

using System.Collections.Generic;

namespace Web.ViewModels.HomeViewModels
{
    public class IndexViewModel
    {
        public IEnumerable<Job> Jobs { get; set; }
    }
}

ApplicantsAndJobs/Web/ViewModels/Job.cs
 
using System;

namespace Web.ViewModels
{
    public class Job
    {
        public int JobId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Company { get; set; }
        public DateTime PostedDate { get; set; }
        public string Location { get; set; }
    }
}

ApplicantsAndJobs/Web/ViewModels/JobApplicant.cs
namespace Web.ViewModels
{
    public class JobApplicant
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public int ApplicantId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
    }
}

ApplicantsAndJobs/Web/ViewModels/JobsViewModels/ApplySuccessViewModel.cs
namespace Web.ViewModels.JobsViewModels
{
    public class ApplySuccessViewModel
    {
        public Job Job { get; }
        public long RecentApplicantCount { get; }

        public ApplySuccessViewModel(Job job, long recentApplicantCount)
        {
            Job = job;
            RecentApplicantCount = recentApplicantCount;
        }
    }
}

ApplicantsAndJobs/Web/ViewModels/JobsViewModels/ApplyViewModel.cs
 

namespace Web.ViewModels.JobsViewModels
{
    public class ApplyViewModel
    {
        public Job Job { get; }
        public User Applicant { get; }

        public ApplyViewModel(Job job,User applicant)
        {
            Job = job;
            Applicant = applicant;
        }
    }
}

ApplicantsAndJobs/Web/ViewModels/JobsViewModels/JobApplicationViewModel.cs
 

namespace Web.ViewModels.JobsViewModels
{
    public class JobApplicationViewModel
    {
       public User Applicant { get; set; }
       public Job Job { get; set; }
    }
}

ApplicantsAndJobs/Web/ViewModels/User.cs
namespace Web.ViewModels
{
    public class User
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Avatar { get; set; }
    }
}

ApplicantsAndJobs/Web/Controllers/HomeController.cs
 
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using Web.Services;
using Web.ViewModels.HomeViewModels;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IJobService _jobService;
 

        public HomeController(IJobService jobService)
        {
            _jobService = jobService;
         
        }

        public async Task<IActionResult> Index()
        {
            return View(new IndexViewModel { Jobs = await _jobService.GetJobs() });
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ApplicantsAndJobs/Web/Controllers/JobsController.cs
using System;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Services;
using Web.ViewModels;
using Web.ViewModels.JobsViewModels;

namespace Web.Controllers
{
    public class JobsController : Controller
    {
        private readonly IJobService _jobService;
        private readonly IIdentityService _identityService;

        public JobsController(IJobService jobService, IIdentityService identityService)
        {
            _jobService = jobService;
            _identityService = identityService;
        }

        // GET jobs/apply/5
        [HttpGet("jobs/apply/{id}")]
        public async Task<IActionResult>  Apply(int id)
        {
            var job = await _jobService.GetJob(id);
            var applicant = await _identityService.GetUserAsync("1"); // hardcoded to user we stashed in identity service
            return View(new ApplyViewModel(job,applicant));
        }

        // POST jobs/apply
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Apply(JobApplicationViewModel model)
        {
            await _jobService.AddApplicant(new JobApplicant
            {
                Email = model.Applicant.Email,
                Name = model.Applicant.Name,
                ApplicantId = Convert.ToInt32(model.Applicant.Id),
                JobId = model.Job.JobId
            });

            return RedirectToAction("ApplySuccess",new{jobId=model.Job.JobId,applicantId= model.Applicant.Id });
        }

        // GET jobs/apply/success/5
        [HttpGet("jobs/apply/success/{id}")]
        public async Task<IActionResult> ApplySuccess(int jobId,string applicantId)
        {
            await Task.Delay(500); // give a sec for redis to eventually update
            var job = await _jobService.GetJob(jobId);
            var applicationCount = await _identityService.GetUserApplicationCountAsync(applicantId);
            return View(new ApplySuccessViewModel(job,applicationCount));
        }
    }
}

ApplicantsAndJobs/Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    @model Web.ViewModels.HomeViewModels.IndexViewModel
}

<div class="row">
    <div class="col-md-8">
        <h1>New Jobs (@Model.Jobs.Count())</h1>
        <hr class="no-margin" />
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        @foreach (var job in Model.Jobs)
            {
            <div class="posting">
                <div class="title-container">
                    <h3>@job.Title</h3>
                    <span>@job.Company | @job.Location | posted on @job.PostedDate.ToString("MM/dd/yyyy")</span>
                </div>
                <p class="description">@job.Description</p>
                <a class="btn btn-success" href="@Url.Action("Apply", "Jobs", new {id = job.JobId})" role="button">Apply for this job</a>
                <hr />
            </div>
        }
    </div>
</div>

ApplicantsAndJobs/Web/Views/Jobs/Apply.cshtml
@{
    ViewData["Title"] = "Apply for a gig";
    @model Web.ViewModels.JobsViewModels.ApplyViewModel
}

<div class="row">
    <div class="col-md-6 posting-apply">
        <h2>@Model.Job.Title</h2>
        <p class="post-meta">@Model.Job.Company | @Model.Job.Location | posted on @Model.Job.PostedDate.ToString("MM/dd/yyyy")</p>
        <p>@Model.Job.Description</p>
        <hr />
        <form asp-action="Apply" method="post">
            <p>You're applying as:</p>
            <input type="hidden" asp-for="Applicant.Id" />
            <input type="hidden" asp-for="Job.JobId" />
            <div class="form-group">
                <label>Email address</label>
                <input type="email" class="form-control" asp-for="Applicant.Email" placeholder="Your email" readonly>
            </div>
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" asp-for="Applicant.Name" placeholder="Your name" readonly>
            </div>
            <button type="submit" class="btn btn-success">Apply for this job</button>
        </form>

    </div>
</div>

ApplicantsAndJobs/Web/Views/Jobs/ApplySuccess.cshtml
@{
    ViewData["Title"] = "You've successfully applied to: " + Model.Job.Title;
    @model Web.ViewModels.JobsViewModels.ApplySuccessViewModel
}

<div class="row">
    <div class="col-md-8 application-success text-center">
        <h1>Way to go!</h1>
        <hr/>
        <p class="summary-description">You've successfully applied to <strong>@Model.Job.Company</strong> for the position of <strong>@Model.Job.Title</strong>.</p>
        <p class="summary-recent-count">You've recently applied for <strong class="recent-application-count">@Model.RecentApplicantCount</strong> job(s).</p>
        <a href="@Url.Action("Index", "Home")">Cool, let's go home.</a>
    </div>
</div>

ApplicantsAndJobs/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>